### ISSUE TITLE
Migrate build to use `docker compose`

### ISSUE THREAD

**Issue by mic-max** [open-telemetry/opentelemetry-demo-webstore#24]
The `docker compose build` will build all services on all platforms

- [ ] Create a `docker-compose.yml` at the root of the repository
- [ ] Adapt all services `Dockerfile` files
  - [ ] Remove duplication of `demo.proto` file
  - [ ] Compile protobuf source files during build
- [ ] Testing

References
- https://docs.docker.com/compose/

**Comment by cartersocha** [comment]
Hey @mic-max, what's the status of this? Do you have any key blockers?

**Comment by julianocosta89** [comment]
Hello @mic-max, I've tried to reach out to you via Slack, but I guess here it is better, because we can have it documented.

I'm taken a look at the PR #33 and I saw that there was a lot of changes regarding env vars, dockerfiles and proto files.

Don't you think it would be better to split them up into small PRs?

I've tried to set it up locally with docker compose and I couldn't make it work.
I have tried to make some changes, but still the services are not talking with each other and the traces are not arriving at Jaeger. It seems that the proto changes have affected the behavior of the services.

I've taken your docker compose as start and created a simpler one, just to make the app run.
I've pushed into a branch: 
https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/feature/docker-compose/compose.yml

If you agree I can open a PR, and then we can do the changes you have done in your PR gradually.

What do you think?





[5:05](https://cloud-native.slack.com/archives/D03E101C17X/p1653577528447639)
I don't want to step on your toes, please don't get me wrong.
If you don't agree I can remove the branch and we continue on yours.
You are the boss here :sweat_smile:

**Comment by cartersocha** [comment]
+1 to smaller, targeted PRs. @cijothomas 😉
