### ISSUE TITLE
Add `depends_on` for all services in `compose.yml`

### ISSUE THREAD

**Issue by mic-max** [open-telemetry/opentelemetry-demo-webstore#96]
https://docs.docker.com/compose/compose-file/#depends-on

**Comment by Frapschen** [comment]
hi, some service, like email service , don't depend  on an other service, what should be set in the `depends_on` ? , otelcol?

**Comment by ahayworth** [comment]
> hi, some service, like email service , don't depend on an other service, what should be set in the depends_on ? , otelcol?

👋 Specifically for `emailservice`, I think the following dependencies make sense:
- `emailservice` ---depends on--> `otelcol`: Practically speaking, `emailservice` will work even if `otelcol` is not available, but since the purpose of this demo is to show off OpenTelemetry then I think the dependency makes sense.
- `checkoutservice` ---depends on--> `emailservice`: if `emailservice` is unavailable, I believe the checkout flow will fail.

I can't speak to the others, though.

**Comment by Frapschen** [comment]
got it, I can help the issue

**Comment by mic-max** [comment]
Looks like this is done!
